### PR TITLE
Fixed that album covers are not displayed when the music is on the SD card.

### LINKED ISSUE #40: Music covers are not displayed
### Steps to reproduce
1. Open App
2. Have music with cover in storage

### Expected behaviour
- The music cover is displayed

### Actual behaviour
- The music cover is not displayed (for example the file manager displays them)

### Environment data
Android version: 9

Device-Model: Moto G6

App version: 4.0.5

### Screenshot
Screenshot_20210117-172322

### PR DESCRIPTION
**Pull request by Beowulf2**
fixes #40 
The permission for WRITE_EXTERNAL_STORAGE was missing in the Android manifest, so the covers were not displayed.

### CODE REVIEW

**Comment by Beowulf2** [comment]
I also improved a few things in the german translation, sorry that it is in this pull request, I forgot that new commits are included in this pull request...

**Comment by HardcodeCoder** [comment]
Yup I did remive the Write permission since we were targetting android 10 and soon 11. So apparently, we need write permissions to display album art in devices < 10.

**Comment by Beowulf2** [comment]
I mean the permission can be in the manifest and just doesn't matter in Android >11 and I mean for Android 10 you also need the permission, right?

**Comment by HardcodeCoder** [comment]
I tested on Android 10 and it doesn't required `WRITE` permissions to display album art.
I think the issue is, when trying to display album art using the `MediaStore`, `Glide` writes the album art in `Music/.thumbnails/ ` inside the internal storage. As of android 10 (due to the nature of scope storage) we don't need write permission when writing thumbnails, where as in Android 9 and lower, we explicitly need `WRITE` permission.

I am not sure if this is what actually happens, but I remember on Android 8, album art were not getting displayed unless I add the `WRITE` permission. And by mistake I removed that in V4.0.4

Anyways, I will merge this now.

**Pull request merged**
