### PR TITLE
Changed navigationBarColor in values-v23 

### PR DESCRIPTION
**Pull request by makkussu**
Hi there!

First of all, thank you for developing Pulse Music. It is the most lightweight and simple music app with pleasant UI I've ever used.

I made changes to themes.xml file in values-v23 folder. I made navigation bar color pure white because translucent one looks kind of weird and does not fit together with the app.

Feedback is appreciated

### CODE REVIEW

**Comment by makkussu** [comment]
I have also added a working GitHub CI/CD for automatic package deployment

**Comment by HardcodeCoder** [comment]
Up until API 27, navigation bar icon color is set to white and cannot be changed. So, we cannot make navigation bar background white.

**Comment by makkussu** [comment]
Here is the preview of the app with those settings enabled:

photo5976460517692257097


The app is tested on
- Android 7.0, API24
- Huawei Honor 6A, DLI-L22

It looks like the navigation bar icons change the color automatically.

**Comment by HardcodeCoder** [comment]
Some custom skins can detect and change the colors, but the default android implementation does not automatically changes the color.

**Pull request closed without merging**
